/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisStepComponent: typeof import('./src/components/data/upload/cleaning/AnalysisStepComponent.vue')['default']
    AssistantMessage: typeof import('./src/components/chat/message/AssistantMessage.vue')['default']
    AssistantText: typeof import('./src/components/chat/message/AssistantText.vue')['default']
    AssistantToolCall: typeof import('./src/components/chat/message/AssistantToolCall.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessages: typeof import('./src/components/chat/ChatMessages.vue')['default']
    CleaningStepComponent: typeof import('./src/components/data/upload/cleaning/CleaningStepComponent.vue')['default']
    CleaningStepIndicator: typeof import('./src/components/data/upload/cleaning/CleaningStepIndicator.vue')['default']
    CleaningSuggestionItem: typeof import('./src/components/data/upload/cleaning/CleaningSuggestionItem.vue')['default']
    CompleteStepComponent: typeof import('./src/components/data/upload/cleaning/CompleteStepComponent.vue')['default']
    DatabaseConnectionStep: typeof import('./src/components/data/upload/DatabaseConnectionStep.vue')['default']
    DataQualityReport: typeof import('./src/components/data/upload/cleaning/DataQualityReport.vue')['default']
    DatasetSelector: typeof import('./src/components/chat/DatasetSelector.vue')['default']
    DataSourceHeader: typeof import('./src/components/data/DataSourceHeader.vue')['default']
    DataSourceSearchBar: typeof import('./src/components/data/DataSourceSearchBar.vue')['default']
    DataSourceTable: typeof import('./src/components/data/DataSourceTable.vue')['default']
    EditDataSourceDialog: typeof import('./src/components/data/EditDataSourceDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconInfo: typeof import('@element-plus/icons-vue')['Info']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FieldMappingsGrid: typeof import('./src/components/data/upload/cleaning/FieldMappingsGrid.vue')['default']
    FileUploadStep: typeof import('./src/components/data/upload/FileUploadStep.vue')['default']
    FlowPanel: typeof import('./src/components/chat/FlowPanel.vue')['default']
    FlowPanel1: typeof import('./src/components/chat/FlowPanel1.vue')['default']
    MCPConnectionForm: typeof import('./src/components/mcp/MCPConnectionForm.vue')['default']
    MCPManager: typeof import('./src/components/chat/MCPManager.vue')['default']
    PreviewDataDialog: typeof import('./src/components/data/PreviewDataDialog.vue')['default']
    QualitySummaryCards: typeof import('./src/components/data/upload/cleaning/QualitySummaryCards.vue')['default']
    ReportGenerationDialog: typeof import('./src/components/chat/report/ReportGenerationDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveWorkflowDialog: typeof import('./src/components/workflow/SaveWorkflowDialog.vue')['default']
    SessionEditDialog: typeof import('./src/components/chat/SessionEditDialog.vue')['default']
    SessionSidebar: typeof import('./src/components/chat/SessionSidebar.vue')['default']
    TemplateUploadDialog: typeof import('./src/components/chat/report/TemplateUploadDialog.vue')['default']
    UploadMethodSelector: typeof import('./src/components/data/upload/UploadMethodSelector.vue')['default']
    UploadStepComponent: typeof import('./src/components/data/upload/cleaning/UploadStepComponent.vue')['default']
    UserMessage: typeof import('./src/components/chat/message/UserMessage.vue')['default']
    WorkflowExecutionResult: typeof import('./src/components/workflow/WorkflowExecutionResult.vue')['default']
    WorkflowManager: typeof import('./src/components/workflow/WorkflowManager.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
