/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisStepComponent: typeof import('./src/components/data/upload/cleaning/AnalysisStepComponent.vue')['default']
    AssistantMessage: typeof import('./src/components/chat/message/AssistantMessage.vue')['default']
    AssistantSuggestions: typeof import('./src/components/chat/message/AssistantSuggestions.vue')['default']
    AssistantText: typeof import('./src/components/chat/message/AssistantText.vue')['default']
    AssistantToolCall: typeof import('./src/components/chat/message/AssistantToolCall.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessages: typeof import('./src/components/chat/ChatMessages.vue')['default']
    CleaningStepComponent: typeof import('./src/components/data/upload/cleaning/CleaningStepComponent.vue')['default']
    CleaningStepIndicator: typeof import('./src/components/data/upload/cleaning/CleaningStepIndicator.vue')['default']
    CleaningSuggestionItem: typeof import('./src/components/data/upload/cleaning/CleaningSuggestionItem.vue')['default']
    CompleteStepComponent: typeof import('./src/components/data/upload/cleaning/CompleteStepComponent.vue')['default']
    DatabaseConnectionStep: typeof import('./src/components/data/upload/DatabaseConnectionStep.vue')['default']
    DataQualityReport: typeof import('./src/components/data/upload/cleaning/DataQualityReport.vue')['default']
    DatasetSelector: typeof import('./src/components/chat/DatasetSelector.vue')['default']
    DataSourceHeader: typeof import('./src/components/data/DataSourceHeader.vue')['default']
    DataSourceSearchBar: typeof import('./src/components/data/DataSourceSearchBar.vue')['default']
    DataSourceTable: typeof import('./src/components/data/DataSourceTable.vue')['default']
    Deepseek: typeof import('./src/components/icons/Deepseek.vue')['default']
    EditDataSourceDialog: typeof import('./src/components/data/EditDataSourceDialog.vue')['default']
    ElTag: typeof import('element-plus/es')['ElTag']
    FieldMappingsGrid: typeof import('./src/components/data/upload/cleaning/FieldMappingsGrid.vue')['default']
    FileUploadStep: typeof import('./src/components/data/upload/FileUploadStep.vue')['default']
    FlowPanel: typeof import('./src/components/chat/FlowPanel.vue')['default']
    MCPConnectionForm: typeof import('./src/components/mcp/MCPConnectionForm.vue')['default']
    MCPManager: typeof import('./src/components/chat/MCPManager.vue')['default']
    Model: typeof import('./src/components/icons/Model.vue')['default']
    ModelList: typeof import('./src/components/chat/ModelList.vue')['default']
    ModelSelectDialog: typeof import('./src/components/chat/ModelSelectDialog.vue')['default']
    PreviewDataDialog: typeof import('./src/components/data/PreviewDataDialog.vue')['default']
    QualitySummaryCards: typeof import('./src/components/data/upload/cleaning/QualitySummaryCards.vue')['default']
    ReportGenerationDialog: typeof import('./src/components/chat/report/ReportGenerationDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveWorkflowDialog: typeof import('./src/components/workflow/SaveWorkflowDialog.vue')['default']
    SessionEditDialog: typeof import('./src/components/chat/SessionEditDialog.vue')['default']
    SessionSidebar: typeof import('./src/components/chat/SessionSidebar.vue')['default']
    TemplateUploadDialog: typeof import('./src/components/chat/report/TemplateUploadDialog.vue')['default']
    UploadMethodSelector: typeof import('./src/components/data/upload/UploadMethodSelector.vue')['default']
    UploadStepComponent: typeof import('./src/components/data/upload/cleaning/UploadStepComponent.vue')['default']
    UserMessage: typeof import('./src/components/chat/message/UserMessage.vue')['default']
    WorkflowManager: typeof import('./src/components/workflow/WorkflowManager.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
