services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./external:/app/external
      - ./uploads:/app/uploads
    environment:
      - DREMIO_BASE_URL=http://dremio:9047
      - DREMIO_USERNAME=dremio
      - DREMIO_PASSWORD=dremio123
      - DREMIO_EXTERNAL_DIR=/app/external
    depends_on:
      - dremio

  dremio:
    image: dremio/dremio-oss:latest
    ports:
      - "9047:9047" # UI 端口
      - "31010:31010" # Arrow Flight 端口
    volumes:
      - dremio_data:/opt/dremio/data # 持久化数据
      - dremio_conf:/opt/dremio/conf # 持久化配置
      - ./external:/external # 挂载外部目录
    environment:
      - DREMIO_HEAP_SIZE_MB=4096 # 设置堆内存大小
      - DREMIO_MAX_DIRECT_MEMORY_MB=8192 # 设置直接内存大小
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data # 持久化 PostgreSQL 数据

volumes:
  dremio_data:
  dremio_conf:
  postgres_data:
