services:
  # Dremio 服务
  dremio:
    image: dremio/dremio-oss:latest
    restart: unless-stopped
    ports:
      - '9047:9047' # UI 端口
      - '32010:32010' # Arrow Flight 端口
    volumes:
      - dremio_data:/opt/dremio/data # 持久化数据
      - dremio_conf:/opt/dremio/conf # 持久化配置
      - ./external:/external # 挂载外部目录
    environment:
      - DREMIO_HEAP_SIZE_MB=4096 # 设置堆内存大小
      - DREMIO_MAX_DIRECT_MEMORY_MB=8192 # 设置直接内存大小
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsSL -o /dev/null --max-time 5 http://localhost:9047 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Redis 服务 (缓存)
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  backend_data:
  dremio_data:
  dremio_conf:
