services:
  # 后端服务
  backend:
    image: ghcr.io/wyf7685/2025-A09/backend:latest
    restart: unless-stopped
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backend_data:/app/data
      - external_data:/external
    environment:
      - HOST=0.0.0.0
      - PORT=8081 # see nginx.conf
      - MAX_WORKERS=1
      - DREMIO_BASE_URL=http://dremio:9047
      - DREMIO_USERNAME=user
      - DREMIO_PASSWORD=password123
      - DREMIO_EXTERNAL_DIR=/external
      - DREMIO_EXTERNAL_NAME=external
      - DOCKER_RUNNER_IMAGE=ghcr.io/wyf7685/2025-A09/executor:latest
      - REDIS_HOST=redis
    depends_on:
      dremio:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsSL -o /dev/null --max-time 5 http://localhost:8081/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  # 前端服务 (Nginx)
  frontend:
    image: ghcr.io/wyf7685/2025-A09/frontend:latest
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_healthy

  # Dremio 服务
  dremio:
    image: dremio/dremio-oss:latest
    restart: unless-stopped
    ports:
      - '9047:9047' # UI 端口
    volumes:
      - dremio_data:/opt/dremio/data # 持久化数据
      - dremio_conf:/opt/dremio/conf # 持久化配置
      - external_data:/external # 挂载外部目录
    environment:
      - DREMIO_HEAP_SIZE_MB=4096 # 设置堆内存大小
      - DREMIO_MAX_DIRECT_MEMORY_MB=8192 # 设置直接内存大小
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsSL -o /dev/null --max-time 5 http://localhost:9047 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Redis 服务 (缓存)
  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  backend_data:
  dremio_data:
  dremio_conf:
  external_data:
