FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    fonts-wqy-microhei \
    fonts-wqy-zenhei \
    fonts-arphic-ukai \
    fonts-arphic-uming \
    fontconfig \
    && rm -rf /var/lib/apt/lists/* \
    && fc-cache -f -v

RUN pip install --no-cache-dir \
    numpy pandas matplotlib seaborn "scipy<1.16" "statsmodels<=0.15"

ADD ./docker/executor.py /executor.py
